name: ci

on: [push, pull_request]

jobs:
  ci-php:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        swoole:
          [
            4.6-php7.2,
            4.6-php7.3,
            4.6-php7.4,
            4.6-php8.0,
            4.5-php7.1,
            4.5-php7.2,
            4.5-php7.3,
            4.5-php7.4,
            4.5-php8.0,
            4.4-php7.1,
            4.4-php7.2,
            4.4-php7.3,
            4.4-php7.4,
          ]
    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          ./.github/prepare-test.sh swoole
          docker exec kafka1 /opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --create --partitions 3 --replication-factor 1 --topic queue-imi-1
          docker exec kafka1 /opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --create --partitions 3 --replication-factor 1 --topic QueueTest1
      - name: test
        run: docker exec swoole composer test
      - name: print logs
        if: failure()
        run: |
          docker exec swoole php .github/print-logs.php
          ls example/.runtime
          ls example/.runtime/logs
          cat example/.runtime/logs/2021-05-04.log
